//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApllication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestApllication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=BINHLT\TEST_DB;Initial Catalog=COMMON;User ID=sa;Password=Administrator@;.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMON.
        /// </summary>
        internal static string DataLogCommon {
            get {
                return ResourceManager.GetString("DataLogCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thất bại: Sai tên đăng nhập hoặc mật khẩu.
        /// </summary>
        internal static string MSG_ERR_001 {
            get {
                return ResourceManager.GetString("MSG_ERR_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thất bại: Có lỗi phát sinh khi đăng nhập.
        /// </summary>
        internal static string MSG_ERR_002 {
            get {
                return ResourceManager.GetString("MSG_ERR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo account thất bại: Username đã tồn tại trong hệ thống.
        /// </summary>
        internal static string MSG_ERR_003 {
            get {
                return ResourceManager.GetString("MSG_ERR_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo account thất bại: Lỗi không xác định.
        /// </summary>
        internal static string MSG_ERR_004 {
            get {
                return ResourceManager.GetString("MSG_ERR_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thất bại: Hãy nhập tài khoản/Mật khẩu.
        /// </summary>
        internal static string MSG_ERR_005 {
            get {
                return ResourceManager.GetString("MSG_ERR_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thất bại: Có lỗi phát sinh khi tạo tài khoản.
        /// </summary>
        internal static string MSG_ERR_006 {
            get {
                return ResourceManager.GetString("MSG_ERR_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản thất bại: Hãy nhập tài khoản/Mật khẩu.
        /// </summary>
        internal static string MSG_ERR_007 {
            get {
                return ResourceManager.GetString("MSG_ERR_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy nhập license!.
        /// </summary>
        internal static string MSG_ERR_008 {
            get {
                return ResourceManager.GetString("MSG_ERR_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký license thất bại: License đã tồn tại trong hệ thống.
        /// </summary>
        internal static string MSG_ERR_009 {
            get {
                return ResourceManager.GetString("MSG_ERR_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký license thất bại: Có lỗi khi lấy thông tin ngày hết hạn.
        /// </summary>
        internal static string MSG_ERR_010 {
            get {
                return ResourceManager.GetString("MSG_ERR_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký license thất bại: Lỗi không xác định.
        /// </summary>
        internal static string MSG_ERR_011 {
            get {
                return ResourceManager.GetString("MSG_ERR_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xảy ra lỗi không xác định.
        /// </summary>
        internal static string MSG_ERR_012 {
            get {
                return ResourceManager.GetString("MSG_ERR_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua license thất bại: Lỗi không xác định.
        /// </summary>
        internal static string MSG_ERR_013 {
            get {
                return ResourceManager.GetString("MSG_ERR_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký license thất bại: Hãy nhập license có tồn tại trong hệ thống.
        /// </summary>
        internal static string MSG_ERR_014 {
            get {
                return ResourceManager.GetString("MSG_ERR_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký license thất bại: License được nhập đã được sử dụng bởi tài khoản khác.
        /// </summary>
        internal static string MSG_ERR_015 {
            get {
                return ResourceManager.GetString("MSG_ERR_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dùng thử.
        /// </summary>
        internal static string MSG_ITEM_001 {
            get {
                return ResourceManager.GetString("MSG_ITEM_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đã mua.
        /// </summary>
        internal static string MSG_ITEM_002 {
            get {
                return ResourceManager.GetString("MSG_ITEM_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn là bản {0}. License của bạn còn thời hạn trong {1} ngày.
        /// </summary>
        internal static string MSG_LIC_INFO_001 {
            get {
                return ResourceManager.GetString("MSG_LIC_INFO_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License của bạn đã hết hạn.
        /// </summary>
        internal static string MSG_LIC_INFO_002 {
            get {
                return ResourceManager.GetString("MSG_LIC_INFO_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc địa chỉ IP của bạn đã nhập quá số lần quy định và đã bị khóa.
        /// </summary>
        internal static string MSG_LIC_INFO_003 {
            get {
                return ResourceManager.GetString("MSG_LIC_INFO_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn không đăng nhập trên đúng địa chỉ IP đã đăng ký. Bạn không thể sử dụng các chức năng của phiên bản license.
        /// </summary>
        internal static string MSG_LIC_INFO_004 {
            get {
                return ResourceManager.GetString("MSG_LIC_INFO_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn chưa có license.
        /// </summary>
        internal static string MSG_LIC_INFO_005 {
            get {
                return ResourceManager.GetString("MSG_LIC_INFO_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ IP của bạn đã nhập quá số lần quy định và đã bị khóa.
        /// </summary>
        internal static string MSG_LIC_INFO_006 {
            get {
                return ResourceManager.GetString("MSG_LIC_INFO_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.
        /// </summary>
        internal static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
    }
}
